name: workflow run

on:
  workflow_run:
    workflows:
      - Hello
    types:
      - completed
jobs:
  main:
    name: main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))
