---
name: Push payload

on:
  push:
    branches: [main, development]

jobs:
  push-job:
    name: Push Step
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.ref_name) }}
        run: echo "$GITHUB_CONTEXT"
